apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    app: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  strategy: {}
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://elastic:9200
        - name: LOGGING_QUIET
          value: "true"
        - name: SERVER_NAME
          value: kibana.divolte-divolte
        image: docker.elastic.co/kibana/kibana:6.4.0
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
      hostname: kibana
      restartPolicy: Always
      subdomain: divolte-divolte
status: {}
