apiVersion: batch/v1
kind: Job
metadata:
  name: put-categories
spec:
  template:
    spec:
      containers:
        - name: put-categories
          image: python:3.6
          workingDir: /shop
          volumeMounts:
            - mountPath: /shop
              name: divolte-shop
          command: ["bash -c 'pip install requests && python catalog-builder/put-categories.py \
                                                 data/categories/animals.json \
                                                 data/categories/architecture.json \
                                                 data/categories/cars.json \
                                                 data/categories/cities.json \
                                                 data/categories/flowers.json \
                                                 data/categories/landscape.json \
                                                 data/categories/nautical.json'"]
      restartPolicy: Never
      volumes:
        - name: divolte-shop
          hostPath:
            # directory location on host
            path: /Users/bas/code/gdd/shop
            # this field is optional
            type: Directory
  backoffLimit: 4