apiVersion: batch/v1
kind: Job
metadata:
  name: put-categories
spec:
  template:
    spec:
      containers:
      - env:
        - name: SHOP_API_URL
          value: "http://shop-api:8080/api"

        name: put-categories
        image: shop_catalog-builder:latest
        imagePullPolicy: Never
          #workingDir: /shop
          #volumeMounts:
          #  - mountPath: /shop
          #     name: divolte-shop
          # command: ["bash"]
          # args: ["-c", "pip install requests && python catalog-builder/put-categories.py --api-base-url http://shop-api:8080/api data/categories/animals.json data/categories/architecture.json data/categories/cars.json data/categories/cities.json data/categories/flowers.json data/categories/landscape.json data/categories/nautical.json"]

      restartPolicy: Never

      # volumes:
      #   - name: divolte-shop
      #     hostPath:
      #       path: /Users/bas/code/gdd/shop
      #       type: Directory
      initContainers:
        - name: wait-for-shop-api-service
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup shop-api; do echo waiting for shop api; sleep 10; done;']
        - name: wait-for-shop-api-ping
          image: busybox:1.28
          command: ['sh', '-c', 'until wget -q --spider "http://shop-api:8080/api/status/ping"; do echo waiting for API ping; sleep 10; done;']
  backoffLimit: 4
