apiVersion: batch/v1
kind: Job
metadata:
  name: put-categories
spec:
  template:
    spec:
      containers:
        - name: put-categories
          image: python:3.6
          workingDir: /shop
          volumeMounts:
            - mountPath: /shop
              name: divolte-shop
          command: ["bash"]
          args: ["-c", "pip install requests && python catalog-builder/put-categories.py --api-base-url http://shop-api:8080/api data/categories/animals.json data/categories/architecture.json data/categories/cars.json data/categories/cities.json data/categories/flowers.json data/categories/landscape.json data/categories/nautical.json"]
      restartPolicy: Never
      volumes:
        - name: divolte-shop
          hostPath:
            path: /Users/bas/code/gdd/shop
            type: Directory
      initContainers:
        - name: wait-for-shop-api-service
          image: busybox:1.28
          command: ['sh', '-c', 'until nslookup shop-api; do echo waiting for shop api; sleep 10; done;']
  backoffLimit: 4
